create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  name text not null,
  company text not null,
  country text not null,
  whatsapp text not null,
  email text,
  consent boolean not null default false,
  "sourcePath" text,
  created_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  quote_id text unique not null,
  contact jsonb not null,
  items jsonb not null,
  note text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.wholesale_requests (
  id bigint generated by default as identity primary key,
  request_id text unique not null,
  name text not null,
  company text not null,
  country text not null,
  whatsapp text not null,
  email text,
  budget text not null,
  "targetMarket" text not null,
  categories jsonb not null,
  style text not null,
  notes text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.quotes enable row level security;
alter table public.wholesale_requests enable row level security;
