"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";

const categories = ["Rings", "Earrings", "Necklaces", "Bracelets", "Charms", "Body jewelry", "Accessories"];

export function WholesaleForm() {
  const [error, setError] = useState(""); const [requestId, setRequestId] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const payload = { name: form.get("name"), company: form.get("company"), country: form.get("country"), whatsapp: form.get("whatsapp"), email: form.get("email"), budget: form.get("budget"), targetMarket: form.get("targetMarket"), categories: form.getAll("categories"), style: form.get("style"), notes: form.get("notes") }; const response = await fetch("/api/wholesale", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || "Unable to submit your request."); return; } setRequestId(data.requestId); }
  if (requestId) return <div className="wholesale-success"><CheckCircle2 /><p className="eyebrow">Request received</p><h2>Your store brief is with our team.</h2><div className="quote-id">{requestId}</div><p>We will use your market, budget and style direction to prepare the next conversation.</p></div>;
  return <form className="wholesale-form" onSubmit={submit}><div className="form-grid"><label><span>Name</span><input name="name" required /></label><label><span>Company / store</span><input name="company" required /></label><label><span>Country / region</span><input name="country" required /></label><label><span>WhatsApp</span><input name="whatsapp" required placeholder="+1 555 000 0000" /></label><label><span>Email <small>Optional</small></span><input name="email" type="email" /></label><label><span>Opening order budget</span><select name="budget" required defaultValue=""><option value="" disabled>Select range</option><option>Under $1,000</option><option>$1,000–$3,000</option><option>$3,000–$10,000</option><option>$10,000+</option></select></label><label className="full"><span>Target market / customer</span><input name="targetMarket" required placeholder="Example: US online boutique, women 20–35" /></label></div><fieldset><legend>Categories to include</legend><div className="checkbox-grid">{categories.map((category) => <label key={category}><input type="checkbox" name="categories" value={category} /><span>{category}</span></label>)}</div></fieldset><label><span>Style direction</span><textarea name="style" rows={3} required placeholder="Minimal, colorful enamel, statement, vintage, everyday basics…" /></label><label><span>Other requirements <small>Optional</small></span><textarea name="notes" rows={3} placeholder="Packaging, target delivery date or best-selling references" /></label>{error && <p className="form-error">{error}</p>}<button className="button button-accent" disabled={loading}>{loading ? "Sending…" : "Send store brief"}<ArrowRight /></button></form>;
}
